---
version: '3'

services:
  grpc-server:
    image: grpc-server
    ports:
      - "8000:8000"
    networks:
      - grpc-network
    environment:
      - GRPC_SERVER_HOST=0.0.0.0
      - GRPC_SERVER_PORT=8000

  grpc-client:
    image: grpc-client
    depends_on:
      - grpc-server
    networks:
      - grpc-network
    environment:
      - GRPC_SERVER_HOST=grpc-server
      - GRPC_SERVER_PORT=8000

networks:
  grpc-network:
    driver: bridge

